[project]
name = "04-feature-hash"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "ruff>=0.14.13",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "ty>=0.0.12",
]
